### ISSUE TITLE
Edits to compile

### ISSUE THREAD

**Issue by Defragster** [nailbuster/myWebServer#1]
I like the looks of the library and got it working - though I can't get 'flashupdate' OTA to work. It is in admin, no password mode, but just prints 'flashupdate' and never presents the 'browse' that works on the FTP page.  FTP works to read/write/delete - great!

The big problem was the '==' stopping assignment, see below.

It also doesn't like this line as a valid NULL compare:
if (root["ssid"].asString() != "") { //verify good json info                                               

I got into 'wifisetup' and that worked, then it showed correct time. Does your IDE ever hold open files in the TIME library so that it can't recompile? 
"GetFileAttributesEx i:\tcode\libraries\Time\DateStrings.cpp i:\tcode\libraries\Time\Time.h: The filename, directory name, or volume label syntax is incorrect."

I made these edits to my copy to get it to compile past errors and two warnings:
@@ -154,7 +154,7 @@ String ICACHE_FLASH_ATTR MyWebServerClass::urlencode(String str)
    char code0;
    char code1;
    char code2;
    for (int i = 0; i < str.length(); i++) {
    for (unsigned int i = 0; i < str.length(); i++) {
@@ -802,9 +800,9 @@ bool MyWebServerClass::WiFiLoadconfig()
            ssid = root["ssid"].asString();
            password = root["password"].asString();
            if (String(root["dhcp"].asString()).toInt() == 1) dhcp = true; else dhcp = false;
            IP[0] == String(root["ip_0"].asString()).toInt(); IP[1] == String(root["ip_1"].asString()).toInt(); IP[2] == String(root["ip_2"].asString()).toInt(); IP[3] == String(root["ip_3"].asString()).toInt();
            Netmask[0] == String(root["nm_0"].asString()).toInt(); Netmask[1] == String(root["nm_1"].asString()).toInt(); Netmask[2] == String(root["nm_2"].asString()).toInt(); Netmask[3] == String(root["nm_3"].asString()).toInt();
            Gateway[0] == String(root["gw_0"].asString()).toInt(); Gateway[1] == String(root["gw_1"].asString()).toInt(); Gateway[2] == String(root["gw_2"].asString()).toInt(); Gateway[3] == String(root["gw_3"].asString()).toInt();
            IP[0] = String(root["ip_0"].asString()).toInt(); IP[1] = String(root["ip_1"].asString()).toInt(); IP[2] = String(root["ip_2"].asString()).toInt(); IP[3] = String(root["ip_3"].asString()).toInt();
            Netmask[0] = String(root["nm_0"].asString()).toInt(); Netmask[1] = String(root["nm_1"].asString()).toInt(); Netmask[2] = String(root["nm_2"].asString()).toInt(); Netmask[3] = String(root["nm_3"].asString()).toInt();
            Gateway[0] = String(root["gw_0"].asString()).toInt(); Gateway[1] = String(root["gw_1"].asString()).toInt(); Gateway[2] = String(root["gw_2"].asString()).toInt(); Gateway[3] = String(root["gw_3"].asString()).toInt();
            if (String(root["grabntp"].asString()).toInt() == 1) useNTP = true; else useNTP = false;

```
        ntpServerName = root["ntpserver"].asString();
```

@@ -826,6 +824,7 @@ bool MyWebServerClass::WiFiLoadconfig()
            return true;
        }
    } //file exists;  
    return true;

**Comment by nailbuster** [comment]
thanks...I haven't had issues with the IDE 'holding' onto the Time libraries (or other libraries).  

The OTA flashing works here(i just tried it)....are you using the sample html files from project?  under utility/flash you should see a button to choose local file (select bin) and then press Upload.  It should pause a bit while uploading the file and then flash/restart auto.

I'm planning on adding support from flashing bins  that are on spiffs folder (via the filebrowser)...soon.

thanks for letting me know about the ==  I'll update it.

I'm using ide 1.6.5 so you might get some more warnings errors in newer ide builds....

let me know.

**Comment by Defragster** [comment]
I'm on IDE 1.6.7 - new tools/warnings indeed. The TIME issue is something I have not seen before - I have to re-copy the files to compile again. Odd issue.

Apparently I'm missing a step on getting the external sample HTML to run against the device's IP?  I'm only hitting the internal sketch page entry points.

I set an admin pwd - now I just get fault restarts, will have to redo the SPIFF to kill the config?

**Comment by nailbuster** [comment]
strange....wonder if its a 1.6.7 issue...works fine here (with pass, etc)....  the html files should just be placed in the root directory.   once you hit the root it should show you the index.html file....

if you still have access you can use /formatspiff  on your device ip to format the spiff...

**Comment by Defragster** [comment]
As I was writing I thought to assume that HTML would go on the SPIFF - had not done that.

I'll redump my old code over serial and the SPIFF image and, then go back to yours after putting the HTML on the root.

**Comment by nailbuster** [comment]
just to be clear....all html files are 'served' from the root of the spiffs.  To get the files onto the spiffs you use the integrated filebrowser that is displayed once it connects to your network.
let me know how it goes....

**Comment by Defragster** [comment]
@nailbuster - I get that now - a note in read.me to that effect would have gotten me there sooner.

Missing that detail initially : (not knowing how) I found the internally supported : server.on("/", handleRoot) [HandleFileBrowser();] and info.html, serverlog to work - and wrongly assumed 'flashupdate' should work the same.

I'll add the HTML to my SPIFFS image when I push the new one over and be in much better shape.  I will miss the IDE friendly 'direct OTA upload' I got from the BasicOTA.ino sample, having to go through the browser to transfer a bin.

I'm running a custom built Teensy_3.2 ESP8266 that currently only has 1M flash - it is working well with 768 code and 256 SPIFFS.  Did you work with PJRC to get the TIME to work on ESP8266?

**Comment by nailbuster** [comment]
yes, I need to add a full 'getting started' wiki page....
for over the air programming....you could use curl (win32 app) to transfer your compiled bins easier.

I just create a batch file like this:

curl -i -X POST -F "data=@myprogram.bin" http://192.168.1.36/flashupdate
pause

I was under the impression you needed more than 1 MB flash if you wanted to do OTA and have room for spiffs....I could be wrong as all my esp8266 have 4MB flash.

**Comment by Defragster** [comment]
All seems functional - rewrote SPIFFS with your HTML - no PWD for now. Edited sketch to include RGB light cycling, it also shows time away from the loop(), page draws show: 177ms, 359ms, 2324ms (info.html) away from loop.

BTW: On 1MB with 256KB spiffs I can OTA upload fine this 306KB BIN - it should work up to half of 716KB of code space. I'm waiting for updated 4MB flash version, until then the SPIFFS fills quickly.

Using the staging 2.1.0-rc2 build of the ESP8266 lib and IDE 1.6.7 I have it building and OTA Web through the myWebServer with the "git clone https://github.com/esp8266/Arduino.git esp8266" to get the hardware\esp8266com as indicated on : https://github.com/esp8266/Arduino.

Still having file issues with TIME lib files on building - have to recopy from the ZIP each time.  Cannot build my OLD OTA code on that machine - the update to the staging version broke ESP8266 there.

May try an edit to platform.txt to put in CURL instead of PYTHON for auto upload.

**Comment by Defragster** [comment]
Made a working batch file for CURL to OTA to myWebServer.  I added curl to the path. It can't run from the IDE though because this OTA w/flashupdate isn't supported to grab the IP to the ports list when the IDE starts up:
- %1 is the full bin path name , %2 is the last part of the IP (the IDE supplied the full IP).
- curl -i -X POST -F data=@%1 http://192.168.1.%2/flashupdate
- I did the same for IDE ready Python script and they work the same - each is unique to the code running on the ESP8266, but I could switch back and forth and have one load the other.

If the myWebServer responded to the BasicOTA 'ping' the IDE does on startup - it would get listed to the ports, and then a custom uploader could work from edited Platform.txt

**Comment by nailbuster** [comment]
It is possible to still use the BasicOTA (update by ide) with the server library.  Just add the calls in your INO main file and it'll work (i tried it).

just call ArduinoOTA.begin(); after myWebServer.begin;  and add the ArduinoOTA.handle(); after the myWebServer.handle() within loop.  

I wouldn't use the IDE OtA method on released code(good for debug/programming), because it would add more services and could cause more instabilities....perhaps wrap it up with a #define

**Comment by nailbuster** [comment]
FYI...I've just updated library to support OTA via IDE with a #define.  See header to enable/disable.  Let me know if works for you...

**Comment by Defragster** [comment]
Works :: Great, Agreed - Very handy for development - perhaps the #define should be under #debug as a hint? 
I considered adding that - but wasn't sure about conflicts.  It adds ~5KB, compiles fine, shows up in Ports and receives OTA via IDE.
Just three warnings during compile for unused vars: code2@161, sent@245, sent@339
