### ISSUE TITLE
Network Configuration with NTP 'Daylight Savings' - wrong time

### ISSUE THREAD

**Issue by Defragster** [nailbuster/myWebServer#3]
I'm not seeing my local time reflect the one hour clock change for savings time in the 'Network Information' server info.html?

Under "Network Configuration"  / NTP configure I have indicated Yes to 'Daylight Savings'.

**Comment by nailbuster** [comment]
I've updated with support for North American DST....

**Comment by Defragster** [comment]
Cool - will try it in the coming hours

**Comment by Defragster** [comment]
How many hours in 6 months+ .... Finally tested this to work!
Thanks.
