### ISSUE TITLE
Encrypt password fields in json files.

### ISSUE THREAD

**Issue by Lymkin** [nailbuster/myWebServer#7]
I know you have to authenticate before you have access, but if a browser was left open someone could just browse the .json files in plain text.  Any possibility of adding functionality to encrypt "password" fields before they are saved in the .json file?

Loving your project so far BTW!

**Comment by nailbuster** [comment]
good idea...I think a simple solution would be to 'hide' the config file being downloaded or browse-able...that way it won't affect current methods....

something like files starting with $ will be system only files....

**Comment by Defragster** [comment]
A 'system only file' would be a nice feature to secure data from WiFi viewing.

**Comment by nailbuster** [comment]
I've added support for admin pages only.  See new option in wifi config pages...doesn't solve the encryption part but will look at that later....

To make your own files admin access only just put '$$$' (without quotes) anywhere in filename.
